header: null
agent: ???
environment: ???
test_environment: null
trainer:
  _target_: tonic.Trainer
before_training: null
after_training: null
parallel: 1
sequential: 1
seed: 0
checkpoint: 'last'
checkpoint_output_dir: null